### ISSUE TITLE
Cant make it work 

### ISSUE THREAD

**Issue by Deepankar1993** [bpocallaghan/notify#2]
I tried every thing in the guide but there are no notification on the returned view using laravel 5.5 with bootstrap 4

**Comment by bpocallaghan** [comment]
Hi @lorddanger 

Thank you for trying out.
Have a look at the [notify.blade.php](https://github.com/bpocallaghan/notify/blob/master/resources/views/notify.blade.php) file.
I totally forgot to add it in the documentation - but look at the `@section('scripts')` section. This means you have to have that in your master layout. Have a look at the [admin.blade.php](https://github.com/bpocallaghan/laravel-admin-starter/blob/master/resources/views/layouts/admin.blade.php) layout file (line 73).

If you want to test it without adding that - you can copy the contents of `notify.blade.php` (only the script section) or to `dump(session('notify.title'))` in the blade.php to see if the session variables gets set.

The other thing to keep in mind - you will have to include the assets as well (also in that [admin starter project](https://github.com/bpocallaghan/laravel-admin-starter).

I am sorry - do realize I will need to update the documentation and setup to make it easier.

Please let me know if this helped or if I can be more specific / update the documentation and package a bit.

Thank you.

**Comment by Deepankar1993** [comment]
yes one of the things that I have did was 
@yield('scripts')
and 
used 
```
php artisan vendor:publish --provider="Bpocallaghan\Notify\NotifyServiceProvider" --tag=view
php artisan vendor:publish --provider="Bpocallaghan\Notify\NotifyServiceProvider" --tag=public
```
then on my layout blade ie app.blade.php
added 
<link href="{{ asset('vendor/notify/notify.css') }}" rel="stylesheet">
<script src="{{ asset('vendor/notify/notify.js') }}"></script>

I have looked into the starter project all the code from notify.js is also there in admin.js

Before the issue 

notify()->...
was working on the controllers only the display was the issue 

however, it's working now with above-mentioned steps and also I had to change the css to be specific 
  `background-color`
for .alert-success ,info,warning,danger or else it was every light

**Comment by bpocallaghan** [comment]
Hi @lorddanger 
Glad its working for you.
Please let me know if you have any suggestions / ideas to make it better / easier to use.
This package started off only for my personal use and thought to share it - so have not really sit and think to make it 'super easy to use for everyone' :)
Happy coding!
